POT/SemestralnaPraca_BettingApp/FriBettingWebApp/FriBettingWebApplication/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using FriBettingWebApplication.Dto.Request;
using FriBettingWebApplication.Dto.Response;
using FriBettingWebApplication.Dto.Response.Page;
using FriBettingWebApplication.Models;
using FriBettingWebApplication.Security;
using Newtonsoft.Json;

namespace FriBettingWebApplication.Controllers
{
    public class MatchesController : Controller
    {
        private readonly HttpClient _client = new HttpClient();

        public ActionResult Index()
        {
            return View("MatchList");
        }

        public ActionResult NewMatch()
        {
            return View();
        }

        public async Task<ActionResult> Evaluation([FromUri] EvaluateMatchRequest evaluateMatchRequest)
        {
            var query = HttpUtility.ParseQueryString(string.Empty);
            query["matchId"] = evaluateMatchRequest.MatchId == null ? "0" : evaluateMatchRequest.MatchId.Value.ToString();

            var url = API_CONF.API_URL + "matches/parts?" + query.ToString();

            _client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", JwtSecurityManager.ApplicationJwtToken);

            var responseJson = await _client.GetStringAsync(url);

            var response = JsonConvert.DeserializeObject<List<MatchPartResponse>>(responseJson);

            return View("Evaluation", new MatchEvaluationModel
            {
                MatchId = evaluateMatchRequest.MatchId ?? 0,
                MatchPartsIds = response == null ? new List<int>() : response.Select(e => e.MatchPartId).ToList()
            });
        }

        public async Task<ActionResult> MatchList([FromUri] GetMatchesFilteredRequest getMatchesFilteredRequest)
        {
            var query = HttpUtility.ParseQueryString(string.Empty);
            query["Page"] = getMatchesFilteredRequest.Page.ToString();
            query["Size"] = getMatchesFilteredRequest.Size.ToString();
            query["FromDate"] = getMatchesFilteredRequest.FromDate?.ToString("MM/dd/yyyy");
            query["ToDate"] = getMatchesFilteredRequest.ToDate?.ToString("MM/dd/yyyy");

            var url = API_CONF.API_URL + "matches?" + query.ToString();

            _client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", JwtSecurityManager.ApplicationJwtToken);

            var responseJson = await _client.GetStringAsync(url);

            var response = JsonConvert.DeserializeObject<MatchesPageResponse>(responseJson);

            return View("MatchList", new MatchesTableModel
            {
                Matches = response.Matches,
                Size = getMatchesFilteredRequest.Size ?? 10,
                Page = getMatchesFilteredRequest.Page ?? 0,
                Count = response.Count,
                FromDate = getMatchesFilteredRequest.FromDate ?? DateTime.MinValue,
                ToDate = getMatchesFilteredRequest.ToDate ?? DateTime.MaxValue
            });
        }

    }
}

POT/SemestralnaPraca_BettingApp/FriBettingWebApp/FriBettingWebApplication/Controllers/TicketsController.cs
using System.Web.Mvc;

namespace FriBettingWebApplication.Controllers
{
    public class TicketsController : Controller
    {

        public ActionResult Index()
        {
            return View("MyTicket");
        }

        public ActionResult MyTicket()
        {
            return View();
        }

        public ActionResult EvaluatedTickets()
        {
            return View();
        }

    }
}

POT/SemestralnaPraca_BettingApp/FriBettingWebApp/FriBettingWebApplication/Controllers/UsersController.cs
using System.Web.Mvc;

namespace FriBettingWebApplication.Controllers
{
    public class UsersController : Controller
    {
        public ActionResult Index()
        {
            return MyAccount();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult MyAccount()
        {
            return View();
        }
    }
}

POT/SemestralnaPraca_BettingApp/FriBettingWebApp/FriBettingWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FriBetting</title>

    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/notify")

    @Scripts.Render("~/bundles/services/sportsService")
    @Scripts.Render("~/bundles/services/usersService")
    @Scripts.Render("~/bundles/services/competitorsService")
    @Scripts.Render("~/bundles/services/matchesService")
    @Scripts.Render("~/bundles/services/ticketsService")

    @Scripts.Render("~/bundles/components/dropdown")

    @Styles.Render("~/bundles/components/dropdown/css")
    @Styles.Render("~/bundles/components/fancyform/css")
    @Styles.Render("~/Content/css")
    <script 
        src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
        integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
        crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-part" class="navbar-collapse collapse">
                <div class="drop matches-dropdown logged-in-menu-item">
                    <div class="option active placeholder matches-dropdown">Zápasy</div>
                    <div class="option matches-dropdown">@Html.ActionLink("Zoznam", "MatchList", "Matches")</div>
                    <div class="option matches-dropdown">@Html.ActionLink("Nový zápas", "NewMatch", "Matches")</div>
                </div>
                <div class="drop tickets-dropdown logged-in-menu-item">
                    <div class="option active placeholder tickets-dropdown">Tikety</div>
                    <div class="option matches-dropdown">@Html.ActionLink("Aktuálne", "MyTicket", "Tickets")</div>
                    <div class="option matches-dropdown">@Html.ActionLink("Vyhodnotené", "EvaluatedTickets", "Tickets")</div>
                </div>
                <div class="drop account-dropdown not-logged-in-menu-item">
                    <div class="option active placeholder account-dropdown">Účet</div>
                    <div class="option account-dropdown">@Html.ActionLink("Registrácia", "Register", "Users")</div>
                    <div class="option account-dropdown">@Html.ActionLink("Prihlásenie", "Login", "Users")</div>
                </div>
                <div class="drop account-dropdown logged-in-menu-item">
                    <div class="option active placeholder account-dropdown">Účet</div>
                    <div class="option account-dropdown"><a href="" onclick="logoutUser()">Odhlásiť</a></div>
                    <div class="option account-dropdown">@Html.ActionLink("Detaily účtu", "MyAccount", "Users")</div>
                </div>
            </div>
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
</div>

@RenderSection("scripts", required: false)
</body>
</html>